---
- name: Configure GRE Tunnel
  hosts: R0
  gather_facts: no
  connection: network_cli
  
  vars_files:
    - ~/ansible-network-labs/r0vars.yml
  
  tasks:
    - name: create tunnel interface to R0
      ios_config:
        lines:
          - 'ip address 172.16.{{ item }}.1 255.255.255.0'
          - 'tunnel source GigabitEthernet2'
          - 'tunnel destination 10.2.{{ item }}.10'
          - 'description Tunnel to R{{ item }}'
        parents: interface Tunnel {{ item }}
      loop: "{{ students }}"
